spring:
  profiles: default

datasource:
  master:
      initialize: true
      driver-class-name: "org.h2.Driver"
      url: "jdbc:h2:mem:test;MVCC=true;DB_CLOSE_DELAY=-1;MODE=MySQL"
      user-name: "sa"
      password: ""
      initial-size: 10
      max-active: 10
      max-idle: 10
      min-idle: 10
      max-wait: 3000
